version: '3.8'

services:
  postgres:
    container_name: postgres_db
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
      POSTGRES_DB: postgres
      TZ: Europe/Moscow
    volumes:
      - postgres:/data/postgres
      - ./pg_hba.conf:/etc/postgresql/postgresql.conf.d/pg_hba.conf
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres: